[package]
name = "lAnon"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8"
regex="1"
indicatif="0.16.2"
walkdir="2.3.2"